name: knuffiworkout
description: A workout app written in Flutter and Firebase.

dependencies:
  firebase_auth: ^4.1.0
  firebase_database: ^10.0.3
  google_sign_in: ^5.4.2
  knuffimap: ^0.2.0
  rxdart: ^0.27.5
  built_value: ^8.4.2
  charts_flutter: ^0.12.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.2
  built_value_generator: ^8.4.0
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.10.0 <3.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/weight.png
