name: knuffiworkout
description: A workout app written in Flutter and Firebase.

dependencies:
  firebase_auth: ^0.4.3
  firebase_database: ^0.3.4
  google_sign_in: ^2.0.1
  rxdart: ^0.16.0
  built_value: ^5.2.1

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^0.8.0
  built_value_generator: ^5.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/weight.png
