name: knuffiworkout
description: A workout app written in Flutter and Firebase.

dependencies:
  firebase_auth: ^0.14.0
  firebase_database: ^3.0.5
  google_sign_in: ^4.0.6
  rxdart: ^0.22.1
  built_value: ^6.7.0
  charts_flutter: ^0.6.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.6.5
  built_value_generator: ^6.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/weight.png
