name: knuffiworkout
description: A workout app written in Flutter and Firebase.

dependencies:
  firebase_auth: ^0.5.20
  firebase_database: ^1.0.4
  google_sign_in: ^3.0.5
  rxdart: ^0.18.1
  built_value: ^6.1.4
  charts_flutter: ^0.4.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/weight.png
