name: knuffiworkout
description: A workout app written in Flutter and Firebase.

dependencies:
  firebase_auth: ^0.8.0
  firebase_database: ^2.0.0
  google_sign_in: ^4.0.0
  rxdart: ^0.20.0
  built_value: ^6.3.0
  charts_flutter: ^0.5.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.2.0
  built_value_generator: ^6.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/weight.png
