name: knuffiworkout
description: A workout app written in Flutter and Firebase.

dependencies:
  firebase_auth: ^0.18.4
  firebase_database: ^4.4.0
  google_sign_in: ^4.5.6
  knuffimap: ^0.1.0
  rxdart: ^0.25.0
  built_value: ^7.1.0
  charts_flutter: ^0.12.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.3
  built_value_generator: ^7.1.0
  flutter_test:
    sdk: flutter

# https://github.com/google/built_value.dart/issues/923
dependency_overrides:
  analyzer: 0.40.4

environment:
  sdk: '>=2.10.0 <3.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/weight.png
